[package]
name = "gc-adapter"
version = "0.1.0"
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
parking_lot = "0.11"
rusb = "0.8"
vigem = { git = "https://github.com/skyfloogle/vigem.git", branch = "fix-error-codes" }
